use_frameworks!


target 'MusicalScaleKit_Tests', :exclusive => true do
  pod 'MusicalScaleKit', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name.include?("Debug")
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
    end
  end
end
